import { useEffect, useMemo, useState } from "react";
import { Download, ChartNoAxesCombined } from "lucide-react";
import { useF1Data } from "@/hooks/useF1Data";
import { downloadF1File, formatF1Date, lapTime, SESSION_NAMES } from "@/lib/f1";
import type { F1Lap, F1Session, LapsData, TrackDriver } from "@/lib/f1";
import { DataStatus, Empty } from "./F1Common";

const COLORS = ["#ba4438", "#4d7c61"];
function LapChart({ series }: { series: { number: string; name: string; laps: F1Lap[] }[] }) {
  const points = series.flatMap((entry) => entry.laps), times = points.map((lap) => lap.lap_duration!);
  if (!points.length) return <Empty>暂无有效圈速可供绘图。</Empty>;
  const minLap = Math.min(...points.map((lap) => lap.lap_number)), maxLap = Math.max(minLap + 1, ...points.map((lap) => lap.lap_number));
  const minTime = Math.floor(Math.min(...times) - 1), maxTime = Math.ceil(Math.max(...times) + 1);
  const x = (lap: number) => 62 + (lap - minLap) / (maxLap - minLap) * 652, y = (time: number) => 250 - (time - minTime) / (maxTime - minTime) * 212;
  return <div className="f1-chart"><svg viewBox="0 0 750 305" role="img" aria-label={`圈速比较，横轴为圈数，纵轴为秒，比较 ${series.map((s) => s.name).join("与")}`}><text x="20" y="20" fill="#77856e" fontSize="11">圈速 / 秒</text>{Array.from({ length: 5 }, (_, i) => { const t = minTime + (maxTime - minTime) * i / 4; return <g key={i}><path d={`M62 ${y(t)}H714`} stroke="#e1e7db"/><text x="51" y={y(t) + 4} textAnchor="end" fill="#7d8975" fontSize="11">{t.toFixed(1)}</text></g>; })}{Array.from({ length: 6 }, (_, i) => { const lap = Math.round(minLap + (maxLap - minLap) * i / 5); return <text key={i} x={x(lap)} y="277" textAnchor="middle" fill="#7d8975" fontSize="11">{lap}</text>; })}<text x="714" y="300" textAnchor="end" fill="#7d8975" fontSize="11">圈数</text>{series.map((entry, i) => <g key={entry.number}><path d={entry.laps.map((lap, index) => `${index === 0 || lap.lap_number > entry.laps[index - 1].lap_number + 1 ? "M" : "L"}${x(lap.lap_number).toFixed(2)},${y(lap.lap_duration!).toFixed(2)}`).join(" ")} fill="none" stroke={COLORS[i]} strokeWidth="2.2"/>{entry.laps.map((lap) => <circle key={lap.lap_number} cx={x(lap.lap_number)} cy={y(lap.lap_duration!)} r="2.2" fill={COLORS[i]}><title>{entry.name} · L{lap.lap_number} · {lapTime(lap.lap_duration)}</title></circle>)}</g>)}</svg><div className="f1-chart-legend">{series.map((entry, i) => <span key={entry.number}><i style={{ background: COLORS[i] }}/>{entry.name}</span>)}</div></div>;
}
export function F1Analysis({ year, sessions, sessionKey, timezone, onSelect }: { year: number; sessions: F1Session[]; sessionKey: string; timezone: string; onSelect: (key: string) => void }) {
  const available = sessions.filter((session) => !session.is_cancelled && Date.parse(session.date_end) + 30 * 60000 < Date.now()).sort((a, b) => b.date_start.localeCompare(a.date_start));
  const selected = sessionKey !== "latest" && available.some((s) => String(s.session_key) === sessionKey) ? sessionKey : String(available.find((s) => s.session_type === "Race")?.session_key || available[0]?.session_key || "");
  const roster = useF1Data<{ drivers: TrackDriver[]; fetchedAt: string; source: string; errors: string[] }>(year >= 2023 && selected ? `action=drivers&year=${year}&session=${selected}` : null);
  const [driverA, setDriverA] = useState(""), [driverB, setDriverB] = useState(""), [applied, setApplied] = useState(""), [excludeOut, setExcludeOut] = useState(true);
  useEffect(() => { setDriverA(""); setDriverB(""); setApplied(""); }, [selected]);
  useEffect(() => { if (roster.data?.drivers.length) { setDriverA(String(roster.data.drivers[0].driver_number)); setDriverB(String(roster.data.drivers[1]?.driver_number || "")); } }, [roster.data]);
  const result = useF1Data<LapsData>(selected && applied ? `action=laps&year=${year}&session=${selected}&drivers=${applied}` : null);
  const series = useMemo(() => applied.split(",").filter(Boolean).map((number) => ({ number, name: roster.data?.drivers.find((driver) => String(driver.driver_number) === number)?.full_name || `#${number}`, laps: (result.data?.laps || []).filter((lap) => String(lap.driver_number) === number && typeof lap.lap_duration === "number" && Number.isFinite(lap.lap_duration) && lap.lap_duration > 0 && (!excludeOut || !lap.is_pit_out_lap)).sort((a, b) => a.lap_number - b.lap_number) })), [applied, roster.data, result.data, excludeOut]);
  function csv() { const values = [["session", "driver_number", "lap_number", "lap_seconds", "sector_1", "sector_2", "sector_3", "pit_out_lap"], ...(result.data?.laps || []).map((lap) => [selected, lap.driver_number, lap.lap_number, lap.lap_duration ?? "", lap.duration_sector_1 ?? "", lap.duration_sector_2 ?? "", lap.duration_sector_3 ?? "", !!lap.is_pit_out_lap])]; downloadF1File(values.map((line) => line.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(",")).join("\r\n"), `f1-${year}-${selected}-laps.csv`, "text/csv;charset=utf-8"); }
  return <section className="f1-section"><div className="f1-section-heading"><div><p className="f1-eyebrow">LOOK BEYOND THE POSITION</p><h2>从圈速里读懂比赛</h2></div><ChartNoAxesCombined size={25}/></div>{year < 2023 ? <Empty>详细圈速分析从 2023 赛季开始。更早赛季仍可查看赛历、成绩和积分榜。</Empty> : <><div className="f1-controls"><label className="f1-session-select">历史场次<select value={selected} onChange={(event) => onSelect(event.target.value)}>{!available.length && <option value="">等待场次数据</option>}{available.map((session) => <option key={session.session_key} value={session.session_key}>{session.location} · {SESSION_NAMES[session.session_name] || session.session_name} · {formatF1Date(session.date_start, timezone)}</option>)}</select></label><label>车手 A<select value={driverA} onChange={(e) => setDriverA(e.target.value)}><option value="">选择车手</option>{roster.data?.drivers.map((driver) => <option key={driver.driver_number} value={driver.driver_number}>{driver.full_name}</option>)}</select></label><label>车手 B<select value={driverB} onChange={(e) => setDriverB(e.target.value)}><option value="">仅分析车手 A</option>{roster.data?.drivers.map((driver) => <option key={driver.driver_number} value={driver.driver_number}>{driver.full_name}</option>)}</select></label><button className="f1-button f1-button-dark" disabled={!driverA || result.loading} onClick={() => setApplied([...new Set([driverA, driverB].filter(Boolean))].join(","))}>开始对比</button></div><DataStatus {...(applied ? result : roster)} timezone={timezone}/>{result.data ? <><div className="f1-analysis-summary">{series.map((entry, index) => <div key={entry.number} style={{ borderTopColor: COLORS[index] }}><small>{entry.name}</small><strong>{entry.laps.length ? lapTime(Math.min(...entry.laps.map((lap) => lap.lap_duration!))) : "—"}</strong><span>本次筛选最快圈 · {entry.laps.length} 个有效圈</span></div>)}</div><div className="f1-section-heading"><label className="f1-checkbox"><input type="checkbox" checked={excludeOut} onChange={(event) => setExcludeOut(event.target.checked)}/>排除出站圈</label><button className="f1-button" onClick={csv}><Download size={14}/>导出原始 CSV</button></div><LapChart series={series}/><details className="f1-lap-details"><summary>查看逐圈与分段数据</summary><div className="f1-table-wrap"><table className="f1-table"><thead><tr><th>车手</th><th>圈</th><th>圈速</th><th>S1</th><th>S2</th><th>S3</th></tr></thead><tbody>{series.flatMap((entry) => entry.laps.map((lap) => <tr key={`${entry.number}-${lap.lap_number}`}><td>{entry.name}</td><td>{lap.lap_number}</td><td className="f1-mono">{lapTime(lap.lap_duration)}</td>{[lap.duration_sector_1, lap.duration_sector_2, lap.duration_sector_3].map((value, i) => <td className="f1-mono" key={i}>{typeof value === "number" && Number.isFinite(value) ? `${value.toFixed(3)}s` : "—"}</td>)}</tr>))}</tbody></table></div></details><p className="f1-footnote">仅绘制有效圈速；出站圈可单独筛除，缺失圈数保留断点。进站、黄旗、交通与轮胎状况都可能影响圈速，图表不会自动推断赛车性能。CSV 保留收到的原始记录。</p></> : !result.loading && <Empty>选择场次与车手，点击“开始对比”读取真实逐圈数据。</Empty>}</>}</section>;
}
