import { useEffect, useMemo, useState } from "react";
import { Activity, Flag, Gauge, Headphones, MapPin, Settings2, Timer, Wind } from "lucide-react";
import { useF1Data } from "@/hooks/useF1Data";
import { formatF1Date, gapTime, lapTime, safeF1Url } from "@/lib/f1";
import type { F1Lap, F1Meeting, F1Session, LiveData, RaceDashboardData, TimingRow } from "@/lib/f1";
import { average, driverStints, lapSummary, pitLaneTime, positive, sectorTime, stintRange, trackStatus, TYRES } from "@/lib/f1-dashboard";
import { DataStatus, Empty, External } from "./F1Common";
import { F1DriverNumber } from "./F1DriverNumber";
import { F1DriverName, F1TeamName } from "./F1Identity";
import { LapChart } from "./F1Analysis";

const FLAGS: Record<string, string> = { GREEN: "绿旗", CLEAR: "解除旗号", YELLOW: "黄旗", "DOUBLE YELLOW": "双黄旗", RED: "红旗", BLUE: "蓝旗", CHEQUERED: "方格旗", "BLACK AND WHITE": "黑白旗" };
const SEGMENTS: Record<number, { color: string; label: string }> = { 2048: { color: "#c4a140", label: "黄段" }, 2049: { color: "#508660", label: "绿段" }, 2051: { color: "#9b65bc", label: "紫段" }, 2064: { color: "#74829a", label: "维修区" } };
const PANELS = { track: "赛道布局", compare: "车手对比", pits: "进站记录", radio: "车队无线电" };
type PanelKey = keyof typeof PANELS;
function readPanels(): Record<PanelKey, boolean> {
  const defaults = { track: true, compare: true, pits: true, radio: true };
  try { const saved = JSON.parse(localStorage.getItem("yukino-f1-panels") || "{}"); for (const key of Object.keys(defaults) as PanelKey[]) if (typeof saved[key] === "boolean") defaults[key] = saved[key]; } catch { /* Use the default layout. */ }
  return defaults;
}
function Tyre({ compound }: { compound?: string }) { const tyre = TYRES[compound || ""]; return <span className="f1-tyre" style={{ color: tyre?.color }} title={tyre?.name || "轮胎未知"}>{tyre?.label || "?"}</span>; }
function value(value: unknown, unit = "", digits = 1) { return typeof value === "number" && Number.isFinite(value) ? `${value.toFixed(digits)}${unit}` : "—"; }
function MiniSectors({ codes }: { codes?: number[] }) {
  return codes?.length ? <span className="f1-mini-sectors" aria-label="微分段记录">{codes.map((code, index) => <i key={index} style={{ background: SEGMENTS[code]?.color || "#e0e5da" }} title={SEGMENTS[code]?.label || "未知"}/>)}</span> : null;
}
function DriverCell({ row, year, selected, onSelect }: { row: TimingRow; year: number; selected: boolean; onSelect: () => void }) {
  return <><button className="f1-focus-driver" onClick={onSelect} aria-pressed={selected} aria-label={`查看${row.full_name || row.name_acronym}的比赛数据`}><i style={{ background: /^[a-f0-9]{6}$/i.test(row.team_colour || "") ? `#${row.team_colour}` : "#748a6b" }}/><F1DriverName fullName={row.full_name || row.name_acronym} compact/><F1DriverNumber year={year} code={row.name_acronym} number={row.driver_number} compact/></button><div className="f1-timing-team"><F1TeamName year={year} name={row.team_name} compact/></div>{(row.dnf || row.dns || row.dsq) && <span className="f1-dnf">{row.dsq ? "DSQ" : row.dns ? "DNS" : "DNF"}</span>}</>;
}
function CircuitPanel({ meeting, session }: { meeting?: F1Meeting; session?: F1Session }) {
  const url = safeF1Url(meeting?.circuit_image), [failed, setFailed] = useState(false);
  useEffect(() => setFailed(false), [url]);
  return <article className="f1-dashboard-card f1-circuit-panel"><div className="f1-panel-heading"><h3><MapPin size={16}/>赛道布局</h3><span>{session?.country_name || "—"}</span></div>{url && !failed ? <img src={url} alt={`${session?.circuit_short_name || meeting?.circuit_short_name}赛道布局`} onError={() => setFailed(true)}/> : <Empty>此场次暂未提供赛道图。</Empty>}<strong>{session?.circuit_short_name || "等待场次"}</strong><p>{meeting?.meeting_name || session?.location || "选择场次查看赛道"}</p>{meeting?.circuit_info_url && <External href={meeting.circuit_info_url}>赛道详细数据</External>}</article>;
}
export function F1RaceDashboard({ live, session, meetings, year, timezone, loading }: { live?: LiveData | null; session?: F1Session; meetings: F1Meeting[]; year: number; timezone: string; loading: boolean }) {
  const eligible = !!session?.session_key && !!live && !live.restricted && ["live", "finished", "unavailable"].includes(live.state) && live.rows.length > 0;
  const details = useF1Data<RaceDashboardData>(eligible ? `action=dashboard&year=${session!.year || year}&session=${session!.session_key}` : null, live?.state === "live" ? 30 : 0);
  // A session switch must never show the preceding session's detail records.
  const data = details.data?.session === session?.session_key && !details.data?.restricted ? details.data : null;
  const [mode, setMode] = useState<"lap" | "sector" | "tyre">("lap"), [filter, setFilter] = useState("");
  const [panels, setPanels] = useState(readPanels), [driverA, setDriverA] = useState<number>(), [driverB, setDriverB] = useState<number>();
  const [showBlue, setShowBlue] = useState(false), [controlFilter, setControlFilter] = useState("all"), [excludeOut, setExcludeOut] = useState(true);
  useEffect(() => { const rows = live?.rows || []; setDriverA(rows[0]?.driver_number); setDriverB(rows[1]?.driver_number); }, [session?.session_key, !!live?.rows.length]);
  useEffect(() => { try { localStorage.setItem("yukino-f1-panels", JSON.stringify(panels)); } catch { /* Preferences remain usable in this page. */ } }, [panels]);
  const allRows = live?.rows || [], actualYear = session?.year || year;
  const rows = allRows.filter((row) => `${row.full_name} ${row.name_acronym} ${row.team_name} ${row.driver_number}`.toLowerCase().includes(filter.toLowerCase()));
  const summaries = useMemo(() => new Map(allRows.map((row) => [row.driver_number, lapSummary(data?.laps || [], row.driver_number)])), [live?.rows, data?.laps]);
  const best = [...summaries.values()].map((entry) => entry.best).filter((lap): lap is F1Lap => !!lap).sort((a, b) => a.lap_duration! - b.lap_duration!)[0];
  const knownLaps = allRows.map((row) => row.laps ?? summaries.get(row.driver_number)?.completed).filter(positive);
  const completed = knownLaps.length ? Math.max(...knownLaps) : undefined;
  const currentStatus = trackStatus(live?.control || [], live?.state === "finished");
  const stints = live?.stints || [], pits = data?.pits || [];
  const pitsKnown = !!data?.available?.pits, radioKnown = !!data?.available?.radio;
  const messages = [...(live?.control || [])].sort((a, b) => b.date.localeCompare(a.date)).filter((event) => (showBlue || event.flag !== "BLUE") && (controlFilter === "all" || controlFilter === "flags" && !!event.flag || controlFilter === "incidents" && /PENALTY|INVESTIGAT|INCIDENT|DELETED|NOTED/i.test(event.message)));
  const meeting = meetings.find((entry) => entry.meeting_key === session?.meeting_key);
  const weather = live?.weather;
  const focused = allRows.find((row) => row.driver_number === driverA), focusedSummary = driverA !== undefined ? summaries.get(driverA) : undefined;
  const series = [...new Set([driverA, driverB].filter((number): number is number => number !== undefined))].map((number) => ({ number: String(number), name: allRows.find((row) => row.driver_number === number)?.name_acronym || `#${number}`, laps: (summaries.get(number)?.ordered || []).filter((lap) => positive(lap.lap_duration) && (!excludeOut || !lap.is_pit_out_lap)) }));
  const detailHint = details.loading ? "正在读取详细记录…" : details.error ? details.error : live?.restricted ? "等待实时数据授权" : live?.state === "upcoming" ? "场次开始后展示记录" : "暂无已公布记录";
  return <div className="f1-dashboard">
    <div className="f1-dashboard-toolbar"><div><span className={`f1-track-state tone-${currentStatus.tone}`}><Flag size={14}/>{currentStatus.label}</span><span className="f1-dashboard-source">{live?.state === "finished" ? "历史场次看板" : "赛事数据看板"} · OpenF1</span></div><details className="f1-panel-settings"><summary><Settings2 size={15}/>面板设置</summary><div>{(Object.keys(PANELS) as PanelKey[]).map((key) => <label key={key}><input type="checkbox" checked={panels[key]} onChange={(event) => setPanels({ ...panels, [key]: event.target.checked })}/>{PANELS[key]}</label>)}</div></details></div>
    <div className="f1-weather-strip" aria-label="赛道天气记录">
      <div><Timer size={16}/><span>气温<strong>{value(weather?.air_temperature, "°C")}</strong></span></div>
      <div><Gauge size={16}/><span>赛道温度<strong>{value(weather?.track_temperature, "°C")}</strong></span></div>
      <div><Activity size={16}/><span>湿度<strong>{value(weather?.humidity, "%")}</strong></span></div>
      <div><Wind size={16}/><span>风速 / 风向<strong>{value(weather?.wind_speed, " m/s")}<small>{value(weather?.wind_direction, "°", 0)}</small></strong></span></div>
      <div><Gauge size={16}/><span>气压<strong>{value(weather?.pressure, " hPa")}</strong></span></div>
      <div><span className="f1-rain-dot"/><span>降雨<strong>{weather?.rainfall === 1 ? "检测到降雨" : weather?.rainfall === 0 ? "未检测到降雨" : "—"}</strong></span></div>
    </div>
    <div className="f1-race-metrics"><div><small>已完成圈数</small><strong>{completed ?? "—"}<em> LAPS</em></strong></div><div><small>记录最快圈</small><strong className="f1-purple">{lapTime(best?.lap_duration)}</strong><span>{best ? `${allRows.find((row) => row.driver_number === best.driver_number)?.name_acronym || `#${best.driver_number}`} · L${best.lap_number}` : "等待有效圈速"}</span></div><div><small>进站记录</small><strong>{pitsKnown ? pits.length : "—"}<em> ENTRIES</em></strong></div><div><small>{live?.state === "finished" ? "记录类型" : "数据检查"}</small><strong className="f1-metric-text">{live?.state === "finished" ? "历史记录" : "30 秒"}</strong><span>{live?.state === "finished" ? "选择场次可回看" : "页面隐藏时暂停"}</span></div></div>
    <div className={`f1-dashboard-grid${!panels.track && !panels.compare ? " without-center" : ""}${!panels.pits && !panels.radio ? " without-events" : ""}`}>
      <article className="f1-dashboard-card f1-timing-panel"><div className="f1-timing-toolbar"><h3>计时塔</h3><input aria-label="筛选计时车手" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="车手 / 车队 / 号码"/></div><div className="f1-timing-tabs" role="tablist" aria-label="计时视图">{([ ["lap", "圈速"], ["sector", "分段"], ["tyre", "轮胎策略"] ] as const).map(([key, label]) => <button key={key} role="tab" aria-selected={mode === key} aria-controls="f1-timing-content" id={`f1-timing-${key}`} onClick={() => setMode(key)}>{label}</button>)}</div>
        <div role="tabpanel" id="f1-timing-content" aria-labelledby={`f1-timing-${mode}`}>{rows.length ? <div className="f1-table-wrap f1-timing-scroll"><table className={`f1-table f1-timing-table f1-dashboard-timing mode-${mode}`}><caption className="sr-only">{mode === "lap" ? "场次计时与最终排名" : mode === "sector" ? "最新逐圈分段记录" : "用胎策略与进站记录"}</caption><thead><tr><th>P</th><th>车手 / 车队</th>{mode === "lap" ? <><th>距领跑 / 前车</th><th>最佳 / 上圈</th><th>胎 / 圈</th></> : mode === "sector" ? <><th>S1</th><th>S2</th><th>S3</th><th>尾速</th></> : <><th>用胎顺序</th><th>进站 / 胎龄</th></>}</tr></thead><tbody>{rows.map((row) => {
          const summary = summaries.get(row.driver_number), rowStints = driverStints(stints, row.driver_number), range = rowStints.length ? stintRange(rowStints[rowStints.length - 1], summary?.completed ?? row.laps) : undefined;
          const rowPits = pits.filter((pit) => pit.driver_number === row.driver_number), sectors = [summary?.latest?.duration_sector_1, summary?.latest?.duration_sector_2, summary?.latest?.duration_sector_3];
          return <tr key={row.driver_number} className={driverA === row.driver_number ? "is-focused" : ""}><td>{row.position ?? "—"}</td><td><DriverCell row={row} year={actualYear} selected={driverA === row.driver_number} onSelect={() => { setDriverA(row.driver_number); if (driverB === row.driver_number) setDriverB(allRows.find((candidate) => candidate.driver_number !== row.driver_number)?.driver_number); }}/></td>{mode === "lap" ? <><td className="f1-mono">{row.position === 1 && session?.session_type === "Race" ? "LEADER" : gapTime(row.gap)}<small>{gapTime(row.interval)}</small></td><td className="f1-mono"><span className={summary?.best && summary.best.lap_duration === best?.lap_duration ? "f1-purple" : ""}>{lapTime(summary?.best?.lap_duration)}</span><small>{lapTime(summary?.last?.lap_duration)}{summary?.last?.is_pit_out_lap ? " OUT" : ""}</small></td><td><Tyre compound={row.compound}/><small>L{row.laps ?? summary?.completed ?? "—"}</small></td></> : mode === "sector" ? <>{sectors.map((sector, index) => <td key={index} className="f1-mono">{sectorTime(sector)}<MiniSectors codes={summary?.latest?.[`segments_sector_${index + 1}` as keyof F1Lap] as number[] | undefined}/></td>)}<td className="f1-mono">{value(summary?.latest?.st_speed, "", 0)}<small>km/h</small></td></> : <><td>{rowStints.length ? <div className="f1-stint-strategy"><div className="f1-tyre-timeline" aria-label="按圈数显示用胎区间">{rowStints.map((stint, index) => { const info = stintRange(stint, index === rowStints.length - 1 ? summary?.completed ?? row.laps : undefined); const max = completed || 1; return info.start && info.length ? <i key={stint.stint_number} style={{ left: `${(info.start - 1) / max * 100}%`, width: `${Math.min(info.length / max * 100, 100)}%`, background: TYRES[stint.compound || ""]?.color || "#bdcbb3" }} title={`${TYRES[stint.compound || ""]?.name || "未知胎"} · L${info.start}–L${info.end}`}/> : null; })}</div><div className="f1-stint-sequence">{rowStints.map((stint, index) => { const stintInfo = stintRange(stint, index === rowStints.length - 1 ? summary?.completed ?? row.laps : undefined); return <span key={stint.stint_number} style={{ borderColor: TYRES[stint.compound || ""]?.color }} title={`${TYRES[stint.compound || ""]?.name || "未知胎"} · ${stintInfo.length ?? "—"} 圈`}><Tyre compound={stint.compound}/><small>{stintInfo.length !== undefined ? `${stintInfo.start}–${stintInfo.end}` : "—"}</small></span>; })}</div></div> : "—"}</td><td className="f1-mono">{pitsKnown ? rowPits.length : "—"} PIT<small>{range?.age ?? "—"} 圈胎龄</small></td></>}</tr>;
        })}</tbody></table></div> : !loading && <Empty>{filter ? "没有符合筛选的车手。" : live?.state === "upcoming" ? "这场比赛尚未开始。" : live?.state === "cancelled" ? "这一场次已取消。" : "暂未收到此场次计时，请使用官方实时计时入口。"}</Empty>}</div>
        <p className="f1-footnote">点击姓名查看车手。S 软胎 · M 中性胎 · H 硬胎 · I 半雨胎 · W 全雨胎。最佳圈取有效记录并排除出站圈，未按赛控删圈校正；正赛微分段通常不提供。未知项显示“—”。</p>
      </article>
      {(panels.track || panels.compare) && <div className="f1-dashboard-center">
        {panels.track && <CircuitPanel meeting={meeting} session={session}/>}
        {panels.compare && <article className="f1-dashboard-card f1-head-to-head"><div className="f1-panel-heading"><h3><Timer size={16}/>车手对比</h3><span>HEAD TO HEAD</span></div><div className="f1-compare-selects">{([ [driverA, setDriverA, "对比车手 A"], [driverB, setDriverB, "对比车手 B"] ] as const).map(([number, setNumber, label]) => <label key={label}>{label}<select aria-label={label} value={number ?? ""} onChange={(event) => setNumber(event.target.value ? Number(event.target.value) : undefined)}><option value="">选择车手</option>{allRows.map((row) => <option key={row.driver_number} value={row.driver_number}>{row.name_acronym} · {row.full_name}</option>)}</select></label>)}</div>{focused && <div className="f1-focused-summary"><F1DriverName fullName={focused.full_name} compact/><div><span>P{focused.position ?? "—"}</span><span>{lapTime(focusedSummary?.best?.lap_duration)}</span><span>{focused.compound ? TYRES[focused.compound]?.name || focused.compound : "未知胎"}</span></div>{live?.state === "finished" && <p className="f1-footnote">场次成绩：{lapTime(focused.duration)}</p>}</div>}<label className="f1-checkbox"><input type="checkbox" checked={excludeOut} onChange={(event) => setExcludeOut(event.target.checked)}/>排除出站圈</label>{series.some((entry) => entry.laps.length) ? <LapChart series={series}/> : <Empty>{detailHint}</Empty>}<p className="f1-footnote">按圈号比较真实圈速；缺失圈保留断点。</p></article>}
      </div>}
      <aside className="f1-dashboard-events">
        <article className="f1-dashboard-card"><div className="f1-panel-heading"><h3><Flag size={16}/>赛事控制</h3><label><input type="checkbox" checked={showBlue} onChange={(event) => setShowBlue(event.target.checked)}/>显示蓝旗</label></div><select className="f1-control-filter" aria-label="赛事控制筛选" value={controlFilter} onChange={(event) => setControlFilter(event.target.value)}><option value="all">全部事件</option><option value="flags">旗帜消息</option><option value="incidents">调查 / 处罚 / 删圈</option></select><div className="f1-control-messages">{messages.length ? messages.map((message, index) => <article key={`${message.date}-${index}`}><small>{formatF1Date(message.date, timezone, { month: undefined, day: undefined, second: "2-digit" })}{message.lap_number ? ` · L${message.lap_number}` : ""}{message.sector ? ` · S${message.sector}` : ""}</small>{message.flag && <span className={`f1-flag flag-${message.flag.toLowerCase().replace(/ /g, "_")}`}>{FLAGS[message.flag] || message.flag}</span>}<p>{message.message}</p></article>) : <p className="f1-footnote">暂无符合筛选的赛事控制消息。</p>}</div></article>
        {panels.pits && <article className="f1-dashboard-card f1-pit-panel"><div className="f1-panel-heading"><h3><Timer size={16}/>进站记录</h3><span>{pitsKnown ? `${pits.length} 次记录` : "PIT LANE"}</span></div><div className="f1-pit-averages"><span>通道平均<strong>{pitsKnown ? value(average(pits.map(pitLaneTime)), "s", 2) : "—"}</strong></span><span>停车平均<strong>{pitsKnown ? value(average(pits.map((pit) => pit.stop_duration)), "s", 2) : "—"}</strong></span></div><div className="f1-event-list">{pits.length ? [...pits].reverse().map((pit, index) => { const driver = allRows.find((row) => row.driver_number === pit.driver_number); return <div key={`${pit.date}-${pit.driver_number}-${index}`}><span><b>{driver?.name_acronym || `#${pit.driver_number}`}</b><small>L{pit.lap_number ?? "—"}</small></span><span>通道<strong>{value(pitLaneTime(pit), "s", 2)}</strong></span><span>停车<strong>{positive(pit.stop_duration) ? value(pit.stop_duration, "s", 2) : "—"}</strong></span></div>; }) : <p className="f1-footnote">{pitsKnown ? "该场次没有进站记录。" : data ? "进站数据暂不可用，请刷新详细面板。" : detailHint}</p>}</div><p className="f1-footnote">通道耗时包含驶入与驶出；停车耗时为静止服务时间。</p></article>}
        {panels.radio && <article className="f1-dashboard-card f1-radio-panel"><div className="f1-panel-heading"><h3><Headphones size={16}/>车队无线电</h3><span>TEAM RADIO</span></div><div className="f1-radio-list">{data?.radio.length ? [...data.radio].reverse().map((radio, index) => { const driver = allRows.find((row) => row.driver_number === radio.driver_number), url = safeF1Url(radio.recording_url); return <article key={`${radio.date}-${index}`}><div><b>{driver?.name_acronym || `#${radio.driver_number}`}</b><small>{formatF1Date(radio.date, timezone, { month: undefined, day: undefined, second: "2-digit" })}</small></div>{url ? <audio controls preload="none" src={url} aria-label={`${driver?.full_name || radio.driver_number}车队无线电`}/> : <p>录音地址暂不可用</p>}</article>; }) : <p className="f1-footnote">{radioKnown ? "该场次暂无公开录音。2026 部分赛事未提供无线电数据。" : data ? "无线电数据暂不可用，请刷新详细面板。" : detailHint}</p>}</div><p className="f1-footnote">来源提供的精选原声；点击播放加载录音。</p></article>}
      </aside>
    </div>
    {eligible && <div className="f1-dashboard-detail-status"><span>详细面板</span><DataStatus {...details} timezone={timezone}/></div>}
  </div>;
}
