import { useF1Data } from "@/hooks/useF1Data";
import { raceName, teamColor, formatRaceDate } from "@/lib/f1";
import type { F1Race, ResultsData } from "@/lib/f1";
import { DataStatus, Empty, External } from "./F1Common";
import { F1DriverName, F1TeamName } from "./F1Identity";

export function F1Results({ year, races, round, kind, timezone, onChange }: { year: number; races: F1Race[]; round: string; kind: string; timezone: string; onChange: (values: Record<string, string>) => void }) {
  const result = useF1Data<ResultsData>(`action=results&year=${year}&round=${round}&kind=${kind}`);
  const race = result.data?.race, rows = result.data?.results || [];
  return <section className="f1-section"><div className="f1-section-heading"><div><p className="f1-eyebrow">RACE CLASSIFICATION</p><h2>每一站的答案</h2></div><div className="f1-controls"><label>大奖赛<select value={round} onChange={(event) => onChange({ round: event.target.value })}><option value="last">最近已公布的比赛</option>{races.map((race) => <option key={race.round} value={race.round}>R{race.round} · {raceName(race.raceName)}</option>)}</select></label><label>成绩类别<select value={kind} onChange={(event) => onChange({ kind: event.target.value })}><option value="results">正赛</option><option value="qualifying">排位赛</option><option value="sprint">冲刺赛</option></select></label></div></div><DataStatus {...result} timezone={timezone}/>{race && <div className="f1-result-heading"><div><h3>{raceName(race.raceName)}</h3><p>{race.Circuit.circuitName} · {formatRaceDate(race, timezone)}</p></div><External href={`https://www.formula1.com/en/results/${year}/races`}>官方比赛结果</External></div>}{rows.length > 0 ? <div className="f1-table-wrap"><table className="f1-table"><caption className="sr-only">{race ? raceName(race.raceName) : "比赛"}成绩</caption><thead><tr><th>排名</th><th>车手</th><th>车队</th>{kind === "qualifying" ? <><th>Q1</th><th>Q2</th><th>Q3</th></> : <><th>发车</th><th>圈数</th><th>时间 / 状态</th><th>积分</th></>}</tr></thead><tbody>{rows.map((row) => <tr key={row.Driver.driverId}><td className={row.position === "1" ? "f1-first" : ""}>{row.position}</td><td><span className="f1-driver-name"><i style={{ background: teamColor(row.Constructor.constructorId) }}/><F1DriverName year={year} driver={row.Driver} compact/></span>{row.FastestLap?.rank === "1" && <small className="f1-fastest">最快圈 {row.FastestLap.Time.time}</small>}</td><td><F1TeamName year={year} team={row.Constructor} compact/></td>{kind === "qualifying" ? <><td className="f1-mono">{row.Q1 || "—"}</td><td className="f1-mono">{row.Q2 || "—"}</td><td className="f1-mono">{row.Q3 || "—"}</td></> : <><td>{row.grid === "0" ? "维修区" : row.grid || "—"}</td><td>{row.laps ?? "—"}</td><td className="f1-mono">{row.Time?.time || row.status || "—"}</td><td className="f1-points">{row.points ?? "—"}</td></>}</tr>)}</tbody></table></div> : !result.loading && <Empty>{result.error ? "成绩数据暂时无法读取。" : "该场次尚无已公布成绩，或这一站没有冲刺赛。"}<External href={`https://www.formula1.com/en/results/${year}/races`}>查看官方结果</External></Empty>}</section>;
}
