name = "yukino-speed"
compatibility_date = "2026-10-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "yukino-portal"
database_id = "e069f104-f55e-441f-9907-0106e2100df7"
